name: NodeJS with Webpack

on:
  # schedule:
  #   - cron: "36 13 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-v1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Runner Time
        run: |
          echo "Current Date: $(date +'%Y-%m-%d')"
          echo "Current Time: $(date +'%H:%M:%S')"
          echo "Time Zone: $(date +'%Z %z')"
        
      - name: Example Step
        run: echo "This workflow runs every day at 11 PM"