name: NodeJS with Webpack

on:
  schedule:
    - cron: "36 13 * * *"

jobs:
  build-v1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your desired steps or commands here
      - name: Example Step
        run: echo "This workflow runs every day at 11 PM"